rules:
  - id: express-cookie-session-no-domain
    message: >-
      Default session middleware settings: `domain` not set. It indicates the
      domain of the cookie; use it to compare against the domain of the server
      in which the URL is being requested. If they match, then check the path
      attribute next.
    severity: WARNING
    languages:
      - javascript
      - typescript
    metadata:
      cwe:
        - 'CWE-522: Insufficiently Protected Credentials'
      owasp:
        - 'A02:2017 - Broken Authentication'
        - 'A04:2021 - Insecure Design'
      source-rule-url: 'https://expressjs.com/en/advanced/best-practice-security.html'
      category: security
      technology:
        - express
      cwe2021-top25: true
      subcategory:
        - vuln
      likelihood: HIGH
      impact: LOW
      confidence: MEDIUM
      references:
        - 'https://owasp.org/Top10/A04_2021-Insecure_Design'
      license: 'Commons Clause License Condition v1.0[LGPL-2.1-only]'
      vulnerability_class:
        - Cryptographic Issues
    patterns:
      - pattern-either:
          - pattern-inside: |
              $SESSION = require('cookie-session');
              ...
          - pattern-inside: |
              $SESSION = require('express-session');
              ...
      - pattern: $SESSION(...)
      - pattern-not-inside: '$SESSION(<... {cookie:{domain:...}} ...>,...)'
      - pattern-not-inside: |
          $OPTS = <... {cookie:{domain:...}} ...>;
          ...
          $SESSION($OPTS,...);
      - pattern-not-inside: |
          $OPTS = ...;
          ...
          $COOKIE = <... {domain:...} ...>;
          ...
          $SESSION($OPTS,...);
      - pattern-not-inside: |
          $OPTS = ...;
          ...
          $OPTS.cookie = <... {domain:...} ...>;
          ...
          $SESSION($OPTS,...);
      - pattern-not-inside: |
          $OPTS = ...;
          ...
          $COOKIE.domain = ...;
          ...
          $SESSION($OPTS,...);
      - pattern-not-inside: |
          $OPTS = ...;
          ...
          $OPTS.cookie.domain = ...;
          ...
          $SESSION($OPTS,...);
